name: Seasoning
favicon: null
layout_spectrum: 0.07285499456338584
typography_spectrum: 0.4980982227693225
title: What are those weird packs?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77299007-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#D8BA58'
    - '#526D98'
    - '#FAFEFD'
    - '#F07881'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
