name: Seasoning
favicon: null
layout_spectrum: 0.8261224562302232
typography_spectrum: 0.8458464969880879
style: the-composer
title: What are those weird packs?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77299007-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.730653949547559
  lightness: 0.885662206215784
  saturation: 0.48195482324808836
  rhythmicContrast: 0.781467649852857
purpose:
  - name: null
    item: null
    url: null
