name: Seasoning
favicon: null
layout_spectrum: 0.7127245450392365
typography_spectrum: 0.44351027929224074
style: the-composer
title: What are those weird packs?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77299007-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.4416510390583426
  lightness: 0.07856027851812541
  saturation: 0.4185178349725902
  rhythmicContrast: 0.6272366237826645
purpose:
  - name: null
    item: null
    url: null
